// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TqiiLanguageTest.Data;

#nullable disable

namespace TqiiLanguageTest.Migrations.RegistrationDb
{
    [DbContext(typeof(RegistrationDbContext))]
    [Migration("20260223204146_EnrollmentDate")]
    partial class EnrollmentDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TqiiLanguageTest.ModelsRegistration.RegistrationCohort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnrollmentEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnrollmentStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberStudents")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cohorts");
                });

            modelBuilder.Entity("TqiiLanguageTest.ModelsRegistration.RegistrationCohortPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRegistered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRegistrationSent")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDenied")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRegistrationCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWaitlisted")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrationCohortId")
                        .HasColumnType("int");

                    b.Property<Guid>("RegistrationGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RegistrationPersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationCohortId");

                    b.HasIndex("RegistrationPersonId");

                    b.ToTable("CohortPeople");
                });

            modelBuilder.Entity("TqiiLanguageTest.ModelsRegistration.RegistrationDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Document")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrationTestPersonId")
                        .HasColumnType("int");

                    b.Property<int>("TestName")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationTestPersonId")
                        .IsUnique();

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("TqiiLanguageTest.ModelsRegistration.RegistrationInstruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeOfInstruction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Instructions");
                });

            modelBuilder.Entity("TqiiLanguageTest.ModelsRegistration.RegistrationPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iein")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NativeLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("TqiiLanguageTest.ModelsRegistration.RegistrationTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrationCohortId")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeOfTest")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationCohortId");

                    b.ToTable("RegistrationTests");
                });

            modelBuilder.Entity("TqiiLanguageTest.ModelsRegistration.RegistrationTestPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsProficiencyExemption")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProficiencyExemptionApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProficiencyExemptionDenied")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrationCohortPersonId")
                        .HasColumnType("int");

                    b.Property<int?>("RegistrationTestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationCohortPersonId");

                    b.HasIndex("RegistrationTestId");

                    b.ToTable("RegistrationTestPeople");
                });

            modelBuilder.Entity("TqiiLanguageTest.ModelsRegistration.RegistrationCohortPerson", b =>
                {
                    b.HasOne("TqiiLanguageTest.ModelsRegistration.RegistrationCohort", "RegistrationCohort")
                        .WithMany()
                        .HasForeignKey("RegistrationCohortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TqiiLanguageTest.ModelsRegistration.RegistrationPerson", "RegistrationPerson")
                        .WithMany()
                        .HasForeignKey("RegistrationPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistrationCohort");

                    b.Navigation("RegistrationPerson");
                });

            modelBuilder.Entity("TqiiLanguageTest.ModelsRegistration.RegistrationDocument", b =>
                {
                    b.HasOne("TqiiLanguageTest.ModelsRegistration.RegistrationTestPerson", "RegistrationTestPerson")
                        .WithOne("RegistrationDocument")
                        .HasForeignKey("TqiiLanguageTest.ModelsRegistration.RegistrationDocument", "RegistrationTestPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistrationTestPerson");
                });

            modelBuilder.Entity("TqiiLanguageTest.ModelsRegistration.RegistrationTest", b =>
                {
                    b.HasOne("TqiiLanguageTest.ModelsRegistration.RegistrationCohort", "RegistrationCohort")
                        .WithMany("RegistrationTests")
                        .HasForeignKey("RegistrationCohortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistrationCohort");
                });

            modelBuilder.Entity("TqiiLanguageTest.ModelsRegistration.RegistrationTestPerson", b =>
                {
                    b.HasOne("TqiiLanguageTest.ModelsRegistration.RegistrationCohortPerson", "RegistrationCohortPerson")
                        .WithMany()
                        .HasForeignKey("RegistrationCohortPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TqiiLanguageTest.ModelsRegistration.RegistrationTest", "RegistrationTest")
                        .WithMany()
                        .HasForeignKey("RegistrationTestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RegistrationCohortPerson");

                    b.Navigation("RegistrationTest");
                });

            modelBuilder.Entity("TqiiLanguageTest.ModelsRegistration.RegistrationCohort", b =>
                {
                    b.Navigation("RegistrationTests");
                });

            modelBuilder.Entity("TqiiLanguageTest.ModelsRegistration.RegistrationTestPerson", b =>
                {
                    b.Navigation("RegistrationDocument");
                });
#pragma warning restore 612, 618
        }
    }
}
